# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/lodej_1214437/Pobrane/Linux_Unreal_Engine_5.5.4

TARGETS = \
	Derelict-Android-DebugGame  \
	Derelict-Android-Development  \
	Derelict-Android-Shipping  \
	Derelict-Linux-DebugGame  \
	Derelict-Linux-Development  \
	Derelict-Linux-Shipping  \
	Derelict-LinuxArm64-DebugGame  \
	Derelict-LinuxArm64-Development  \
	Derelict-LinuxArm64-Shipping  \
	Derelict \
	DerelictEditor-Linux-DebugGame  \
	DerelictEditor-Linux-Development  \
	DerelictEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend DerelictEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug DerelictEditor-Linux-Debug


Derelict-Android-DebugGame:
	 $(BUILD) Derelict Android DebugGame  -Project="/home/lodej_1214437/Dokumenty/Unreal Projects/Derelict/Derelict.uproject" $(ARGS)

Derelict-Android-Development:
	 $(BUILD) Derelict Android Development  -Project="/home/lodej_1214437/Dokumenty/Unreal Projects/Derelict/Derelict.uproject" $(ARGS)

Derelict-Android-Shipping:
	 $(BUILD) Derelict Android Shipping  -Project="/home/lodej_1214437/Dokumenty/Unreal Projects/Derelict/Derelict.uproject" $(ARGS)

Derelict-Linux-DebugGame:
	 $(BUILD) Derelict Linux DebugGame  -Project="/home/lodej_1214437/Dokumenty/Unreal Projects/Derelict/Derelict.uproject" $(ARGS)

Derelict-Linux-Development:
	 $(BUILD) Derelict Linux Development  -Project="/home/lodej_1214437/Dokumenty/Unreal Projects/Derelict/Derelict.uproject" $(ARGS)

Derelict-Linux-Shipping:
	 $(BUILD) Derelict Linux Shipping  -Project="/home/lodej_1214437/Dokumenty/Unreal Projects/Derelict/Derelict.uproject" $(ARGS)

Derelict-LinuxArm64-DebugGame:
	 $(BUILD) Derelict LinuxArm64 DebugGame  -Project="/home/lodej_1214437/Dokumenty/Unreal Projects/Derelict/Derelict.uproject" $(ARGS)

Derelict-LinuxArm64-Development:
	 $(BUILD) Derelict LinuxArm64 Development  -Project="/home/lodej_1214437/Dokumenty/Unreal Projects/Derelict/Derelict.uproject" $(ARGS)

Derelict-LinuxArm64-Shipping:
	 $(BUILD) Derelict LinuxArm64 Shipping  -Project="/home/lodej_1214437/Dokumenty/Unreal Projects/Derelict/Derelict.uproject" $(ARGS)

Derelict: Derelict-Linux-Development

DerelictEditor-Linux-DebugGame:
	 $(BUILD) DerelictEditor Linux DebugGame  -Project="/home/lodej_1214437/Dokumenty/Unreal Projects/Derelict/Derelict.uproject" $(ARGS)

DerelictEditor-Linux-Development:
	 $(BUILD) DerelictEditor Linux Development  -Project="/home/lodej_1214437/Dokumenty/Unreal Projects/Derelict/Derelict.uproject" $(ARGS)

DerelictEditor: DerelictEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/lodej_1214437/Dokumenty/Unreal Projects/Derelict/Derelict.uproject" -Game 

.PHONY: $(TARGETS)
